// <auto-generated />
using System;
using HockeyPractice.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HockeyPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903035335_AddDrills")]
    partial class AddDrills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HockeyPractice.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CopiedFromDrillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("DiagramBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagramFileName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "IsArchived");

                    b.ToTable("Drills");
                });

            modelBuilder.Entity("HockeyPractice.Models.DrillTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("DrillId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("DrillTags");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanDrill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PracticePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.HasIndex("PracticePlanId", "SortOrder");

                    b.ToTable("PlanDrills");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTitle")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasEditedByCoach")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PracticePlanId");

                    b.ToTable("PlanLinks");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticePlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("PracticePlanId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("PlanTags");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstViewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PracticePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PracticePlanId", "PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasIndex("PracticePlanId", "ViewerKey")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NULL");

                    b.ToTable("PlanViews");
                });

            modelBuilder.Entity("HockeyPractice.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JerseyNumber")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HockeyPractice.Models.PracticePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PracticeDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "PracticeDateLocal");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("HockeyPractice.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnsubToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmToken");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UnsubToken");

                    b.HasIndex("TeamId", "Email")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("HockeyPractice.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachCodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpotifyPlaylistUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewCodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("HockeyPractice.Models.Drill", b =>
                {
                    b.HasOne("HockeyPractice.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPractice.Models.DrillTag", b =>
                {
                    b.HasOne("HockeyPractice.Models.Drill", "Drill")
                        .WithMany("Tags")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanDrill", b =>
                {
                    b.HasOne("HockeyPractice.Models.Drill", "Drill")
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HockeyPractice.Models.PracticePlan", "PracticePlan")
                        .WithMany("Drills")
                        .HasForeignKey("PracticePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");

                    b.Navigation("PracticePlan");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanLink", b =>
                {
                    b.HasOne("HockeyPractice.Models.PracticePlan", "PracticePlan")
                        .WithMany("Links")
                        .HasForeignKey("PracticePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticePlan");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanTag", b =>
                {
                    b.HasOne("HockeyPractice.Models.PracticePlan", "PracticePlan")
                        .WithMany("Tags")
                        .HasForeignKey("PracticePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticePlan");
                });

            modelBuilder.Entity("HockeyPractice.Models.PlanView", b =>
                {
                    b.HasOne("HockeyPractice.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HockeyPractice.Models.PracticePlan", "PracticePlan")
                        .WithMany("Views")
                        .HasForeignKey("PracticePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PracticePlan");
                });

            modelBuilder.Entity("HockeyPractice.Models.Player", b =>
                {
                    b.HasOne("HockeyPractice.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPractice.Models.PracticePlan", b =>
                {
                    b.HasOne("HockeyPractice.Models.Team", "Team")
                        .WithMany("Plans")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPractice.Models.Subscriber", b =>
                {
                    b.HasOne("HockeyPractice.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HockeyPractice.Models.Team", "Team")
                        .WithMany("Subscribers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HockeyPractice.Models.Drill", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("HockeyPractice.Models.PracticePlan", b =>
                {
                    b.Navigation("Drills");

                    b.Navigation("Links");

                    b.Navigation("Tags");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("HockeyPractice.Models.Team", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("Players");

                    b.Navigation("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
